### ISSUE TITLE
Error message, The naming context specified for this replication operation is invalid

### ISSUE THREAD

**Issue by StefanSa** [MichaelGrafnetter/DSInternals#103]
Hi there,
i come from here:
[https://github.com/improsec/Get-bADpasswords](url)
but get the following error message:
`Replicating AD user data with parameters (DC = 'XX', NC = 'DC=XX,DC=XX')...
The naming context specified for this replication operation is invalid
`

Any idea ?

**Comment by MichaelGrafnetter** [comment]
Yes, you might have provided an incorrect DNS domain name / domain distinguished name. BTW, this parameter will become optional in the next release of DSInternals.
