### ISSUE TITLE
Unclear example in Get-ADKeyCredential.md documentation

### ISSUE THREAD

**Issue by homoSapiensSapiens** [MichaelGrafnetter/DSInternals#104]
The documentation for the Get-ADKeyCredential command, example 6:
`PS C:\> $certificateSubject = 'S-1-5-21-1236425271-2880748467-2592687428-1109/13f787d5-4078-47ee-a6e7-b3af92f76c1e/login.windows.net/383a3889-5bc9-47a3-846c-2b70f0b7fe0e/john@contoso.com'
`
It is unclear where that magic UUIDs came from - Are they the user object GUID, or the Directory's, or something else?
It would be very helpful any clarification on that.

**Comment by MichaelGrafnetter** [comment]
Well, it really IS UNCLEAR unclear where those magic UUIDs came from, as there is no official documentation for it. Luckily, the value of the Subject has actually no effect on the functionality, it only appears in DC logs.
Nevertheless, the first UUID seems to be random and the second one appears to be a constant. So I typically generate it using the following code:
```powershell
$targetAccount = Get-ADUser -Identity john
$certificateSubject = '{0}/{1}/login.windows.net/383a3889-5bc9-47a3-846c-2b70f0b7fe0e/{2}' -f $targetAccount.SID,(New-Guid),$targetAccount.UserPrincipalName
```
