### ISSUE TITLE
Cannot Import Version 4.3

### ISSUE THREAD

**Issue by Hamsterfisch** [MichaelGrafnetter/DSInternals#108]
Hello,

I installed Version 4.3 on Windows Server 2016 and Windows Server 2012 R2. 
Errormessage: 
Import-Module: Could not load file or assembly <powershellpath>\dsinternals.common.dll or one of its dependencies (HRESULT: 0x80131515)
PowerShell Version: 5.1.14393.2636

best regards!

**Comment by MichaelGrafnetter** [comment]
Hi @Hamsterfisch 

I just deployed a clean Windows Server 2016 1607 computer and DSInternals 4.3 from GitHub ran there without any issues. On a new Windows Server 2012 R2 computer, I only needed to update the .NET Framework and install the Universal C Runtime, but it then also ran without any issues. And these components even get installed automatically when Windows Update is enabled.

How did you download the module? Could you please post the exact parameters of `Import-Module` that you are calling it with? See [Submitting Bug Reports](https://github.com/MichaelGrafnetter/DSInternals/blob/master/.github/CONTRIBUTING.md#submitting-bug-reports).

**Comment by Hamsterfisch** [comment]
Hi,

thanks for your reply.

I followed thesese instructions for installing: https://github.com/MichaelGrafnetter/DSInternals#downloads

First, I tried to install the module like this:
![dsinternals](https://user-images.githubusercontent.com/63092673/78421559-d3c00d80-7658-11ea-9adc-682f366e3458.PNG)
I also tried (Same Errormessage):
Install-Module DSInternals
Install-Module DSInternals -RequiredVersion 4.2

Because I could not download it like this, I downloaded the zip file and extracted it into C:\Windows\system32\WindowsPowerShell\v1.0\Modules\

For importing, I followed this example:
https://www.dsinternals.com/en/retrieving-active-directory-passwords-remotely/
I also tried import-module dsinterals -force

**Comment by MichaelGrafnetter** [comment]
You apparently have 2 different issues here.

If you are not able to download packages, check your internet connectivity, including proxy configuration, and TLS settings. The following command helps in some cases:
```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```
But local installation should work under all circumstances. Are you sure that you followed the [instructions](https://github.com/MichaelGrafnetter/DSInternals#offline-module-distribution-powershell-3)? I was able to replicate the HRESULT: 0x80131515 error by not unblocking the ZIP file first. You can try to to this to fix it:

```powershell
Get-ChildItem C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ -Recurse -File | Unblock-File
Import-Module DSInternals
```

If you tried to import the module before unblocking the files, you need to open a new PowerShell console.
