### ISSUE TITLE
Get-ADDBAccount -All -DBPath 'C:\temp\ntds.dit' -BootKey $Key  not working- what should I do?

### ISSUE THREAD

**Issue by boe1** [MichaelGrafnetter/DSInternals#112]
Hello,

I installed the update to powershell 5.1.   

I downloaded the latest zip file to a c:\temp folder
I then extracted the contents to C:\Windows\system32\WindowsPowerShell\v1.0\Modules\DSInternals

I'm running Windows 2012 R2
I ran the command Get-ADDBAccount -All -DBPath 'C:\temp\ntds.dit' -BootKey $Key

I got the following
Get-ADDBAccount : Cannot validate argument on parameter 'BootKey'. The argument is null. Provide a valid value for the
argument, and then try running the command again.
At line:1 char:58
+ Get-ADDBAccount -All -DBPath 'C:\temp\ntds.dit' -BootKey $Key
+                                                          ~~~~
    + CategoryInfo          : InvalidData: (:) [Get-ADDBAccount], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,DSInternals.PowerShell.Commands.GetADDBAccountCommand

**Comment by boe1** [comment]
My bad, I forgot to run $key = Get-BootKey -SystemHivePath  'C:\temp\SYSTEM' first

**Comment by boe1** [comment]
PS - thanks for this great program!

**Comment by MichaelGrafnetter** [comment]
Glad that you have resolved it, @boe1 .
