### ISSUE TITLE
Get-ADDBAccount : Could not decrypt or parse the PEK list.

### ISSUE THREAD

**Issue by bbrucker** [MichaelGrafnetter/DSInternals#113]
Hi,

I used your PowerShell module and made this script to analyze our AD in offline mode : 

```
$dico='C:\pwned-passwords-sha1-ordered-by-count-v6.txt'
$database='C:\system_files\1\ntds.dit'
$output='C:\system_files\1\export.txt'

$key = Get-BootKey -SystemHivePath 'C:\system_files\1\SYSTEM'

Get-ADDBAccount -All -DatabasePath $database -Bootkey $key |
Test-PasswordQuality -WeakPasswordHashesSortedFile $dico -IncludeDisabledAccounts |
Out-File -FilePath $output -Encoding UTF8
```
It worked and generated an output file.

But when I tried with our secondary AD NTDS file, this error appeared "Get-ADDBAccount : Could not decrypt or parse the PEK list.".

The two NTDS files come from shadow copies of the real AD.

## The command/script that caused the error
C:\Users\Administrator\Desktop\test-passwords-ntds.ps1

## Error message
```
Get-ADDBAccount : Could not decrypt or parse the PEK list.
Au caractère C:\Users\Administrateur\Desktop\test-passwords-ntds-avacloud.ps1:9 : 1
+ Get-ADDBAccount -All -DatabasePath $database -Bootkey $key |
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ADDBAccount], FormatException
    + FullyQualifiedErrorId : System.FormatException,DSInternals.PowerShell.Commands.GetADDBAccountCommand
```

## The entire exception stack trace
```Could not decrypt or parse the PEK list.
   à DSInternals.DataStore.DataStoreSecretDecryptor..ctor(Byte[] encryptedPEKListBlob, Byte[] bootKey) dans d:\a\1\s\Src\DSIn
ternals.DataStore\Cryptography\DataStoreSecretDecryptor.cs:ligne 87
   à DSInternals.DataStore.DirectoryAgent.GetSecretDecryptor(Byte[] bootKey) dans d:\a\1\s\Src\DSInternals.DataStore\Director
yAgent.PasswordManagement.cs:ligne 289
   à DSInternals.DataStore.DirectoryAgent.<GetAccounts>d__9.MoveNext() dans d:\a\1\s\Src\DSInternals.DataStore\DirectoryAgent
.cs:ligne 61
   à DSInternals.PowerShell.Commands.GetADDBAccountCommand.ReturnAllAccounts(Byte[] bootKey)
   à System.Management.Automation.CommandProcessor.ProcessRecord()
```

## Version of the DSInternals module
`4.4.1`

## OS on which the command was running
`Microsoft Windows Server 2019 Standard`

## PowerShell version
`5.1.17763.1`

## Other informations
I confirm that I can get the boot key before trying to do the "Get-ADDBAccount" command.

I checked this issue : https://github.com/MichaelGrafnetter/DSInternals/issues/97 and I already tried to change the registry value :

![registre_dsinternals](https://user-images.githubusercontent.com/23634782/97156477-0bb6ab80-1777-11eb-9192-76c9d109ea54.png)

Merging the XML configuration do not resolve my issue.
I also tried to execute the code on another system but the same issue occurred. (Windows 10 Pro and Windows Server 2016)
I asked my superiors another clean version of the NTDS and SYSTEM files but the error persists.

I specify that the following command `Get-ADDBDomainController -DatabasePath` worked for the two files and given me all the information needed.

### The first AD :
> OSName : Windows Server 2012 Standard
> OSVersion : 6.2
> OSVersionMajor : 6
> OSVersionMinor : 2

### The second AD (where issue occurs) :
> OSName : Windows Server 2016 Standard
> OSVersion : 10.0
> OSVersionMajor : 10
> OSVersionMinor : 0

Thank you for your help.

Best regards.

**Comment by MichaelGrafnetter** [comment]
Hi @bbrucker, thanks for the extensive report, that is unfortunate. Could you please double-check that the SYSTEM hive is from the same snapshot as the database you are trying to decrypt? If so, then I have probably incorrectly reverse-engineered the data format in Windows Server 2016 and my code does not cover some rare conditions. There are 2 ways of resolving this issue:

**1. Harder:** You manage to replicate the issue in a test environment and send me ntds.dit and SYSTEM for analysis.
**2. Easier:** You privately send me the data from the exception (`$Error[0].Exception.Data['bootKey']` and `$Error[0].Exception.Data['encryptedPEKListBlob']` if I remember correctly). Note that these values contain no personal information from your organization and sharing them without the database itself poses no security risk.

Also please send me the `InnerException` property.

**Comment by CamFlyerCH** [comment]
Probably not the source of your error, but you have a hash file specified with SHA-1 hashes. I assume the password audit only works with NTLM hashes. So you should get the other version like pwned-passwords-ntlm-ordered-by-hash-v6.txt .
Take a look at [https://github.com/MichaelGrafnetter/DSInternals/blob/master/Documentation/PowerShell/Test-PasswordQuality.md#test-passwordquality](url)

**Comment by bbrucker** [comment]
Hi @CamFlyerCH and thank you for noticing me that.

It seems the issue comes from our SYSTEM file or because DSInternals decodes the boot key incorrectly.
I will let you know how the situation evolves.
