### ISSUE TITLE
HOW TO REGISTER FIDO2 SECURITY KEY TO A SPECIFIC USER IN AZURE ACTIVE DIRECTORY--Registers new FIDO keys in Azure Active Directory.

### ISSUE THREAD

**Issue by deepukgithub** [MichaelGrafnetter/DSInternals#114]
I was able to revoke FIDO2 security key previously registered by the specific user for eg : john@contoso.com 
steps followed are 
PS C:\> Install-Module -Name AzureAD,DSInternals -Force
PS C:\> Connect-AzureAD
PS C:\> $token = [Microsoft.Open.Azure.AD.CommonLibrary.AzureSession]::AccessTokens['AccessToken'].AccessToken
PS C:\> Set-AzureADUserEx -UserPrincipalName 'john@contoso.com' -KeyCredential @() -Token $token

HOW TO REGISTER FIDO2 SECURITY KEY TO A SPECIFIC USER IN AZURE ACTIVE DIRECTORY

**Comment by MichaelGrafnetter** [comment]
I am currently working on this feature. Registering a new security key is way more difficult than removing an existing one.

**Comment by deepukgithub** [comment]
Kindly let me know while you update on this.

**Comment by deepukgithub** [comment]
Kindly help me out when you add this feature "  TO REGISTER FIDO2 SECURITY KEY TO A SPECIFIC USER IN AZURE ACTIVE DIRECTORY "

**Comment by deepukgithub** [comment]
I faced the following errors while executing the scripts

**Comment by deepukgithub** [comment]
![Mass_Provisioning_killotp_Add-3](https://user-images.githubusercontent.com/39602889/98220608-8bf9bf80-1f74-11eb-8b2f-100b66af90d1.PNG)

**Comment by MichaelGrafnetter** [comment]
Have you tried using an empty array `@()` instead of `$null`?

**Comment by deepukgithub** [comment]
Yes, to revoke FIDO2 security key previously registered by the specific user for eg : john@contoso.com
steps followed are
PS C:> Install-Module -Name AzureAD,DSInternals -Force
PS C:> Connect-AzureAD
PS C:> $token = [Microsoft.Open.Azure.AD.CommonLibrary.AzureSession]::AccessTokens['AccessToken'].AccessToken
PS C:> Set-AzureADUserEx -UserPrincipalName 'john@contoso.com' -KeyCredential @() -Token $token


then tried with

PS C:\> $user = Get-AzureADUserEx -UserPrincipalName 'john@contoso.com' -AccessToken $token 
PS C:\> $newCreds = $user.KeyCredentials | where { $PSItem.FidoKeyMaterial.DisplayName -notlike '*YubiKey*' }
PS C:\> Set-AzureADUserEx -UserPrincipalName 'john@contoso.com' -KeyCredential $newCreds -Token $token



showed error for me 
![Mass_Provisioning_killotp_Add-3](https://user-images.githubusercontent.com/39602889/98288685-39002680-1fcd-11eb-926d-5b2440f62a15.PNG)


I was trying TO REGISTER FIDO2 SECURITY KEY TO A SPECIFIC USER IN AZURE ACTIVE DIRECTORY.
Please help me out on this.

**Comment by deepukgithub** [comment]
Can you please help me out for this

**Comment by MichaelGrafnetter** [comment]
I am repeating myself, but the command does not accept `$null`, but your `$newCreds` variable is `$null`. At least that is what the error message says. I therefore asked you, if you tried it with an empty collection `@()` instead. Like in this example:
```powershell
Set-AzureADUserEx -UserPrincipalName *** -KeyCredential @() -Token $token
```

**Comment by deepukgithub** [comment]
yes i tried with an empty collection with command
Set-AzureADUserEx -UserPrincipalName 'john@contoso.com' -KeyCredential @() -Token $token

after this command the fido security key was deleted from the UPN   'john@contoso.com'

If I am wrong please correct me . Can you please help me out for registering fido security key to a user in Azure AD with powershell command

**Comment by MichaelGrafnetter** [comment]
So it is resolved then. You are able to unregister a single FIDO2 key or all keys at once using DSInternals.
As already said several messages ago, I am currently in the process of implementing support for new FIDO2 key registration, but it will take me a month or two.

**Comment by deepukgithub** [comment]
OK Thank you so much , Please help me when you get success on implementing new FIDO2 key registration.

**Comment by deepukgithub** [comment]
Can you please help me out  on implementing new FIDO2 key registration.

**Comment by deepukgithub** [comment]
> 
> 
> So it is resolved then. You are able to unregister a single FIDO2 key or all keys at once using DSInternals.
> As already said several messages ago, I am currently in the process of implementing support for new FIDO2 key registration, but it will take me a month or two.

Can you please help me out on implementing new FIDO2 key registration.

**Comment by EvanMcBroom** [comment]
Hey @deepukgithub, why don't you fork the project, fix the registration issue yourself, and make a pull request. You've been pestering the owner of this project to work on your issue without providing any help yourself. Your insistent messages asking him to fix this issue after he already said that he's been working on it could be considered borderline harassment, and which can be reported to GitHub as spam.

**Comment by deepukgithub** [comment]
@MichaelGrafnetter  I tried some steps below which i found related to this
![Mass_Provioning_FidoKey-Add_PowerShell-1](https://user-images.githubusercontent.com/39602889/101635488-0aec8700-3a50-11eb-82d4-2a2c858c7664.PNG)
![Mass_Provioning_FidoKey-Add_PowerShell-2](https://user-images.githubusercontent.com/39602889/101635491-0c1db400-3a50-11eb-8b5d-d6962af69e39.PNG)

![Mass_Provioning_FidoKey-Add_PowerShell-Code-2](https://user-images.githubusercontent.com/39602889/101635496-0cb64a80-3a50-11eb-8991-01c4189df46b.PNG)
![Mass_Provioning_FidoKey-Add_PowerShell-Code-3](https://user-images.githubusercontent.com/39602889/101635498-0d4ee100-3a50-11eb-9822-bdbec61a0ac9.PNG)
![Mass_Provioning_FidoKey-Add_PowerShell-Code-4](https://user-images.githubusercontent.com/39602889/101635501-0de77780-3a50-11eb-90c3-d750a5682f02.PNG)
![Mass_Provioning_FidoKey-Add_PowerShell-Code-5](https://user-images.githubusercontent.com/39602889/101635502-0e800e00-3a50-11eb-8cb7-3817a57ed3b7.PNG)

**Comment by deepukgithub** [comment]
![Mass_Provioning_FidoKey-Add_PowerShell-Code-6](https://user-images.githubusercontent.com/39602889/101756003-8e16e700-3afb-11eb-8782-f40b4213f815.PNG)

**Comment by deepukgithub** [comment]
@MichaelGrafnetter  Happy New Year.
I tried from my end and can't able to find any success on (Powershell-DSInternals ) FIDO2 key registering for a specific user. I was able to add through PowerShell security sign in option which is attached in previous window.
I hope you will be in progress with the same. If you are able to find any solution then please help me too.

**Comment by deepukgithub** [comment]
Happy New Year.
I tried from my end and can't able to find any success on (Powershell-DSInternals ) FIDO2 key registering for a specific user. I was able to add through PowerShell security sign in option which is attached in previous window.
I hope you will be in progress with the same. If you are able to find any solution then please help me too.


Thanks & Regards,

Deepu K
________________________________

**Comment by deepukgithub** [comment]
Dear Michael,
Appreciate your response. I really did not intend to worry you on this matter. Please do take your own time.


Thanks & Regards,

Deepu K
________________________________

**Comment by yohashi227** [comment]
Dear @MichaelGrafnetter , 
Hello, I'm Yoshi.

We want to provision many FIDO2 key for many Azure AD user.
To do that, we think we need DS Internals and this great implementation. 

Could you please release this implementation for our testing?
We will repot our test result to you.

Thanks & Regards.
Yoshi

**Comment by deepukgithub** [comment]
Dear @MichaelGrafnetter/DSInternals<mailto:DSInternals@noreply.github.com>
Appreciate you for helping us on this implementation.


Thanks & Regards,

Deepu. K
________________________________

**Comment by deepukgithub** [comment]
Dear MichaelGrafnetter,
Kindly release the DS Internals implementation for multi provisioning FIDO2 key with Azure AD users.
Appreciate you for your help.



Thanks & Regards,

Deepu. K




________________________________

**Comment by scureq** [comment]
Hi Michael,

Sorry to bother you. I just came across the same requirement for the current project - registering a new FIDO2 key for a user. I know this is a tricky process. Did you manage to figure something out? 

Many thanks!
Pat

**Comment by Aronsson84** [comment]
Hi @MichaelGrafnetter! Really appreciate your work with DSInternals!
I'm curious around the status for this specific issue, it would be a killer feature :) However I can imagine that is quite complex to fix.

All the best!
//Tony

**Comment by tikesavage** [comment]
any update? this is huge missing feature for Azure. Hardware tokens and Fido Keys are basically unusable  because of the lack of administrative abilities.

**Comment by MichaelGrafnetter** [comment]
After almost finishing the FIDO2 registration functionality, I found out that Microsoft has disabled it in the meantime, for security reasons:

![image](https://github.com/MichaelGrafnetter/DSInternals/assets/8986376/d97500bc-f844-45d6-9990-ca89c8e78b00)

I am not aware if any way around it, so this feature is officially dead.

**Comment by aseigler** [comment]
> After almost finishing the FIDO2 registration functionality, I found out that Microsoft has disabled it in the meantime, for security reasons:
> 
> ![image](https://user-images.githubusercontent.com/8986376/239612201-d97500bc-f844-45d6-9990-ca89c8e78b00.png)
> 
> I am not aware if any way around it, so this feature is officially dead.

Wouldn't this also break the WHfBTools package documented to clean up orphaned WHfB credentials?

**Comment by MichaelGrafnetter** [comment]
> Wouldn't this also break the WHfBTools package documented to clean up orphaned WHfB credentials?

The cmdlet can still be used to selectively remove FIDO2/NGC keys, only the addition of new keys stopped working. You can thank @dirkjanm , who [got this nasty idea](https://twitter.com/_dirkjan/status/1659146636533067778) to use the API in phishing attacks with MFA bypass and reported it to Microsoft.

**Comment by aseigler** [comment]
I guess I will test it myself but I think the way it works is enumerate all keys on the user, remove the keys we don't want, then write back all the keys we want to keep.

**Comment by MichaelGrafnetter** [comment]
Hello, for anyone still interested, Microsoft released a new API last week, which makes administrative registration of FIDO2 security keys possible. I have just published a standalone PowerShell module for this, called [DSInternals.Passkeys](https://www.powershellgallery.com/packages/DSInternals.Passkeys):

![powershell](https://github.com/user-attachments/assets/555a930e-f0bb-4681-b8b4-b3aab4824369)

**Comment by MichaelGrafnetter** [comment]
> does this support Oath tokens?

@tikesavage This new capability only covers Passkeys.
