### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by andrePKI** [MichaelGrafnetter/DSInternals#119]
`install-module dsinternals -Force` gives me `An error has occurred while loading script module DSInternals.Bootstrap because it has a different language mode than the module manifest. The manifest language mode is ConstrainedLanguage and the module language mode is FullLanguage.`

I am not really fluent in this, but to me this reads as an internal inconsistency between module and manifest (?). Or is it just me?

**Comment by MichaelGrafnetter** [comment]
@andrePKI It would seem that PowerShell script execution is blocked on your computer through a policy. All features of DSInternals require Full Language mode and it is impossible to write it differently. I am planning to digitally sign the module in the near future.
