### ISSUE TITLE
Get-ADReplAccount : An item with the same key has already been added

### ISSUE THREAD

**Issue by xoxol4ik** [MichaelGrafnetter/DSInternals#120]
Hi Michael!
please tell me How to fix this problem?

"Get-ADReplAccount : An item with the same key has already been added"

This has already been discussed here #40 , but I have the latest version of DSInternals.
Please help me!

**Comment by MichaelGrafnetter** [comment]
Hi @xoxol4ik, thanks for the report. Could you please provide [more details](https://github.com/MichaelGrafnetter/DSInternals/blob/master/.github/CONTRIBUTING.md#submitting-bug-reports)?

**Comment by MichaelGrafnetter** [comment]
Seems to be related to Issue #118.
