### ISSUE TITLE
How to compare the hashes from users

### ISSUE THREAD

**Issue by Th0masAAnderson** [MichaelGrafnetter/DSInternals#122]
Hello,

fist of all great tool love it. This here is more like a question as a issue.

I'm wondering if there is a way to compare the password hashes from 3 users. 

$user1 = Get-ADReplAccount -SamAccountName user1 -Server DC
$user2 = Get-ADReplAccount -SamAccountName user2 -Server DC
$user3 = Get-ADReplAccount -SamAccountName user3 -Server DC

If I do it like mentioned "$user1 + $user2 + $user3 | Test-PasswordQuality" I only get an error message:
Get-ADReplAccount : Cannot convert 'System.Object[]' to the type 'System.String' required by 
parameter 'SamAccountName'. Specified method is not supported.

Beside this, is there a way to get only the nthash like $user1.nthash or $user1 | select-object NTHash to compare them?

Many thanks in advance.

best regards
Thomas

**Comment by MichaelGrafnetter** [comment]
Hi @Th0masAAnderson, aren't you missing parentheses in your code snippet?
```powershell
($user1 + $user2 + $user3) | Test-PasswordQuality
```

Although the Test-PasswordQuality cmdlet uses the [HashEqualityComparer class](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Src/DSInternals.Common/Cryptography/HashEqualityComparer.cs) for password hash comparison, the easiest way for you would be converting the binary hash to a hexadecimal string using the [ConvertTo-Hex cmdlet](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Documentation/PowerShell/ConvertTo-Hex.md) and doing a string comparison afterwards.

You might also want to have a look at the built-in [Password Hash Export Formats](https://github.com/MichaelGrafnetter/DSInternals/tree/master/Documentation/PowerShell#password-hash-export-formats).

**Comment by Th0masAAnderson** [comment]
Hello Michael,

yes you're right did. missed them.

Just another short question, don't know how else to contact you, where does the replication from the AD are stored? Because if I run Get-ADRepelAccount it tells me it's replicating...local onto the host where I ran the program or on temporary on the DC which one I selected? 

Thank for clarification in advance.

best regards
Thomas
