### ISSUE TITLE
[Question] How can I import DSInternals.Replication.Interop?

### ISSUE THREAD

**Issue by rios0rios0** [MichaelGrafnetter/DSInternals#123]
Hello @MichaelGrafnetter . I'm trying to use the C# code. When I imported some commands to my project, I had an error thrown by DSInternals.Replication... The error was saying: "Can't find DSInternals.Replication.Interop version 4.3.0.0". Ok, I built the DLL from the source and added the reference to my project. When I run again, I have now:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'DSInternals.Replication.Interop, Version=4.3.0.0, Culture=neutral, PublicKeyToken=af7e77ba04a3c166' or one of its dependencies. Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x80131019) ---> System.IO.FileLoadException: Could not load file or assembly 'DSInternals.Replication.Interop, Version=4.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x80131019) ---> System.IO.FileLoadException: Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x80131019)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, Boolean fSkipIntegrityCheck, SecurityContextSource securityContextSource)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly)
   at Costura.AssemblyLoader.ReadFromEmbeddedResources(Dictionary`2 assemblyNames, Dictionary`2 symbolNames, AssemblyName requestedAssemblyName)
   at Costura.AssemblyLoader.ResolveAssembly(Object sender, ResolveEventArgs e)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   --- End of inner exception stack trace ---
   at DSInternals.Replication.DirectoryReplicationClient..ctor(String server, RpcProtocol protocol, NetworkCredential credential)
```
How can I do it? Could you help me?

**Comment by MichaelGrafnetter** [comment]
Check that your assembly targets amd64, as does DSInternals.Replication.Interop.

**Comment by rios0rios0** [comment]
> Check that your assembly targets amd64, as does DSInternals.Replication.Interop.

Yes! I did this...
I had to get the DLL from the PowerShell gallery. Because compiling from the source doesn't work. The public key of the DLL was null and didn't match with TSL expected. Do you know how to solve this?

**Comment by MichaelGrafnetter** [comment]
What about assemblies in the NuGet gallery? Is there any issue with them?
Or you can generate your own signing key pair, see the Keys directory.

**Comment by rios0rios0** [comment]
> What about assemblies in the NuGet gallery? Is there any issue with them?
> Or you can generate your own signing key pair, see the Keys directory.

I used the assemblies in the NuGet gallery. Thank you!
