### ISSUE TITLE
Test-Passwordquality by splatting arguments

### ISSUE THREAD

**Issue by OlivierMasit** [MichaelGrafnetter/DSInternals#125]
Hi Guys, 

Did anyone already tried to pass the arguments to the Test-PasswordQaulity cmdlet using splatting technique @{} ? 
Thank you in advance.

**Comment by aseigler** [comment]
Not sure exactly what you mean, but this works:

```powershell
...
$dsobjects = New-Object System.Collections.Hashtable
# Loop through domains in forest
foreach ($domain in $adforest.Domains)
{
    # Domain controller in current site
    $dc = (Get-ADDomainController -Server $domain).HostName
    
    # Get domain DN for replication
    $dn = (Get-ADDomain -Server $dc).DistinguishedName

    # Sync objects from top of domain naming context using site DC
    Get-ADReplicationAccount -All -NamingContext $dn -Server $dc | ForEach-Object { 
        if ($_.SamAccountType -eq 'User' -and $null -ne $_.NTHash)
        {
            $dsobjects.Add($_.LogonName,$_)
        }
    }
 }

#region PasswordQualityReporting
$report = $dsobjects.Values | Test-PasswordQuality -IncludeDisabledAccounts -WeakPasswordHashesSortedFile $HIBPFile
```

**Comment by OlivierMasit** [comment]
@aseigler Thank you for your reply.
No, I meant splatting all the arguments like:

````powershell
$args = @{
		WeakPasswordHashesSortedFile = "./myhashlist.txt"
		WeakPasswordsFile		     = "./mypwdlist"
		}
$acc | Test-PasswordQuality $args
```
or include the array in the splat
```powershell
Test-PasswordQuality $args
```
I need to generate dynamically a Hashtable to include or not different lists defined in a Json file. That's why I want to use the splatting to pass the arguments to the function.

**Comment by CamFlyerCH** [comment]
@OlivierMasit 
I used splatting sometimes and also mostly forgot this:
Splatted parameter values are stored in named splatting variables, which look like standard variables, but begin with an At symbol (@) instead of a dollar sign ($).  ([about_Splatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-7.1))

Or check https://adamtheautomator.com/powershell-splatting/

**Comment by OlivierMasit** [comment]
@CamFlyerCH,
lol, stupid autocomplete :-)))
Thanks a lot for spotting it out ! You just saved me a lot of time cause I'm not sure when I would have realized it ^^.
Have a great day !
