### ISSUE TITLE
Dependency Loop Detected

### ISSUE THREAD

**Issue by mubix** [MichaelGrafnetter/DSInternals#126]
Trying to install DSInternals on Powershell 7 on Linux / Ubuntu is getting a dependency loop error

```powershell
PS /home/ubuntu> Install-Package dsinternals.common
Install-Package: Dependency loop detected for package 'DSInternals.Common'. 
```

**Comment by MichaelGrafnetter** [comment]
Hi @mubix , unfortunately, DSInternals is not supported on Linux at all, as it heavily utilizes Win32 API for almost everything it does (database layer, replication and LSA over RPC, hashing algorithms).
