### ISSUE TITLE
Windows Server 2022 Database Modification Support

### ISSUE THREAD

**Issue by pbachmann77** [MichaelGrafnetter/DSInternals#127]
Hi there
Is SIDHistory Import supported on Server 2022?

**Error, after Import, can't start Service ntds**
ntdsutil: activate instance ntds
Active instance set to "ntds".
ntdsutil: Semantic database analysis
Could not initialize the Jet engine:  Jet Error -623.
Failed to open DIT for AD DS/LDS instance NTDS. Error -2147418113

**Comment by MichaelGrafnetter** [comment]
Strange. Did you run DSInternals on the same WS2022 system? Are transaction logs (edb*.log) located in the same directory as ntds.dit?

**Comment by aseigler** [comment]
From https://github.com/microsoft/Extensible-Storage-Engine/blob/3bcf428c8a041733043e18fd9ae55cffeba307b2/dev/ese/src/_errstr/errdata.txt#L251

`EXTERNAL_ERR( -623,	State,		JET_errEngineFormatVersionSpecifiedTooLowForDatabaseVersion	 )`

Interesting...

**Comment by pbachmann77** [comment]
> Strange. Did you run DSInternals on the same WS2022 system? Are transaction logs (edb*.log) located in the same directory as ntds.dit? Are other cmdlets from DSInternals working?

Yes, same Machine, 2022 Domain Controller
I changed only one user SID

**Comment by MichaelGrafnetter** [comment]
OK, this really seems to be specific to editing ntds.dit on WS 2022. I will have to deploy a new DC VM and test it myself.

**Comment by MichaelGrafnetter** [comment]
Hi @pbachmann77 , could you please re-test with DSInternals 4.6? Thanks.
