### ISSUE TITLE
Distribute the libraries as a NuGet package

### ISSUE THREAD

**Issue by MichaelGrafnetter** [MichaelGrafnetter/DSInternals#13]
The DSInternals project has been designed to be modular and the helper libraries might be useful in other projects. To make it easier for other developers to use them, these libraries could be distributed in the form of a NuGet package:
- DSInternals.Replication
- DSInternals.DataStore
- DSInternals.SAM

**Comment by nbevans** [comment]
Yes please! I pulled in the Replication libraries manually for now but yes a NuGet would be far nicer.

I understand the need for the PowerShell cmdlets but we wanted to "bake in" the DSInternals Replication library to our tool at a lower level.

**Comment by MichaelGrafnetter** [comment]
OK, @nbevans. Then you could help me with these decisions:

1. How many packages to create? Should I pack all DSInternals.*.dll files into one package or split them into multiple packages?
2. Which framework(s) should I target? Do you think that 4.5.1 is sufficient?
3. Shall the package(s) be strong-name signed or not? When releasing the PowerShell module, I sign all my assemblies + the [CryptSharp library](http://www.zer7.com/software/cryptsharp), because the corresponding [NuGet package](https://www.nuget.org/packages/CryptSharpOfficial/) is not signed. But as soon as I make it a dependency of the DSInternals package, I would not be able to sign it either. I have come up with these solutions:
   1. Distribute CryptSharp dll through the DSInternals package.
   2. Create and release yet another CryptSharp package, signed with my key.
   3. Persuade the author of CryptSharp to sign the package. This would of course be the ideal solution. I just wonder if you could try to contact him, as I currently have no time for that.

**Comment by nbevans** [comment]
1. I would definitely split them since for example we only need the Replication library and it would be annoying if it had to pull in all the Esent dependencies and other stuff too.

2. I'm not 100% sure but 4.5.1 seems good enough to me.

3. I don't see value in signing the assemblies. It just causes the type of pain you've discovered :)

Thanks

**Comment by MichaelGrafnetter** [comment]
Published, see [NuGet Gallery](https://www.nuget.org/profiles/MichaelGrafnetter)! As it is my first experience with creating NuGet packages, I will be glad for any feedback.
I am already aware of a small bug: The DSInternals.Replication.Model assembly has to be manually added into References. I have already fixed it in the source code, but I do not want to do a new NuGet release yet.
