### ISSUE TITLE
Get-BootKey requires admin privileges even with offline audit

### ISSUE THREAD

**Issue by idnahacks** [MichaelGrafnetter/DSInternals#142]
Is there a reason why Get-BootKey requires to be run as an administrator when processing an offline SYSTEM file? I understand the need for SeBackupPrivilege when grabbing the file out of the registry, but not otherwise.

Thanks for the great tool.

**Comment by MichaelGrafnetter** [comment]
Hi, `SeBackupPrivilege` is also required when temporarily mounting the offline registry file.
