### ISSUE TITLE
Reference to Newtonsoft.Json version which contains a public advisory

### ISSUE THREAD

**Issue by danielmak0** [MichaelGrafnetter/DSInternals#148]
Hello,

During a review of DSInternals code, [this advisory](https://github.com/advisories/GHSA-5crp-9r3c-p9vr) was found. Dependabot submitted a PR to address the NuGet version bump on June 22, 2022. Please add this task to the TODO list.

Thanks

**Comment by MichaelGrafnetter** [comment]
Fixed in release 4.8.
