### ISSUE TITLE
Get-ADReplAccount fails against renamed domains

### ISSUE THREAD

**Issue by rmbolger** [MichaelGrafnetter/DSInternals#15]
Get-ADReplAccount (and I presume any other commands that rely on the MS-DRSR protocol) appears to have a problem working against domains that have previously gone through a rename process.  The following error is presented.

```
Get-ADReplAccount : The directory service cannot perform the requested operation because the servers involved are of
different replication epochs (which is usually related to a domain rename that is in progress)
At line:1 char:1
+ Get-ADReplAccount -SamAccountName XXXXXX -domain XXXX -server XXXXX ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ADReplAccount], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,DSInternals.PowerShell.Commands.GetADReplAccountCom
   mand
```

Despite the error message indicating the problem might be related to a rename in progress, this particular domain was renamed successfully about 5 years ago and is not currently still being renamed.  The value of `msDS-RelicationEpoch` on the `nTDSDSA` object for all DCs is currently 1.  If I temporarily clear the value on the DC I'm targetting, the command works as expected (though that DC obviously has broken replication until I set it back).

I'm guessing the code just always uses 0 and perhaps it should query the current value on the target DC first and use that.  If I get some time, I may try submitting a PR for this.

P.S. Love this project. Amazing work.

**Comment by MichaelGrafnetter** [comment]
Thank you very much, @rmbolger, for a thorough bugreport. I actually do not recall dealing with the replication epoch in my code at all. I will try to examine it and find a way to fix it.
I just wonder if you could test the DCSync functionality of mimikatz against that renamed domain of yours, because it does basically the same thing as Get-ADReplAccount.

**Comment by MichaelGrafnetter** [comment]
I just could not wait and I confirm that mimikatz has the same problem...

**Comment by rmbolger** [comment]
Yeah, I didn't have a copy of mimikatz handy at the time. But when I went browsing through the source, I found that same struct, [DRS_EXTENSIONS_INT](https://msdn.microsoft.com/en-us/library/cc228475.aspx), that @gentilwiki mentioned. Figured I'd trace that back and see what was using it.
