### ISSUE TITLE
DSInternals.Replication.Interop.dll - File not found Exception on .NET 7/Core

### ISSUE THREAD

**Issue by umar-ulabs** [MichaelGrafnetter/DSInternals#157]
I installed the packages DSInternals.Replication.  Created instance of  DirectoryReplicationClient and right there it throws. I tried it on some machines. In one Windows server 2016(.NET core 7 app) it doesn't throw, don't know why.  Yours insights much appreciated. Is there something obvious I am missing ? 
![image](https://github.com/MichaelGrafnetter/DSInternals/assets/29075597/0d977d69-13b7-49b2-a01f-2d758e8be486)

**Comment by MichaelGrafnetter** [comment]
Hi @umar-ulabs , DSInternals is currently only compiled for .NET Framework, not .NET (Core) 7. Additionally, the replication stuff is the NuGet package is 64-bit only, so the assembly must be compiled with 64-bit preference over 32-bit. I would like to add support for additional platforms soon.
