### ISSUE TITLE
Password in plain text is missing

### ISSUE THREAD

**Issue by Nikolara97** [MichaelGrafnetter/DSInternals#167]
Hi Michael I was reading your doc: https://www.dsinternals.com/en/retrieving-active-directory-passwords-remotely/ I have done everything from it, but once I run it PlainText (Clear Text) for Active Directory user is empty.. Is there anything that was changed since artical was written. I really need to get my AD users passwords. Thanks in advance.

<img width="365" alt="image" src="https://github.com/MichaelGrafnetter/DSInternals/assets/121571467/a91ca287-64cd-4d53-a292-fded39d11790">

**Comment by MichaelGrafnetter** [comment]
Hello @Nikolara97 , the presence of cleartext passwords in AD database is governed by this [highly discouraged setting](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/store-passwords-using-reversible-encryption). I absolutely doubt that anyone *really needs to get their AD users passwords* for other than malicious reasons, as it would totally compromise AD security.
