### ISSUE TITLE
query by upn rather than samaccount, guid or sid

### ISSUE THREAD

**Issue by kevindelafield** [MichaelGrafnetter/DSInternals#18]
I'd like to be able to search users by upn for DirectoryReplicationClient.GetAccount.

**Comment by MichaelGrafnetter** [comment]
Is this what you had in mind? It will appear in a next release.

**Comment by kevindelafield** [comment]
yes, that is what i was looking for.
thanks!

**Comment by MichaelGrafnetter** [comment]
This change has been just released in v 2.16.

**Comment by kevindelafield** [comment]
Thanks.

Sent from my Verizon, Samsung Galaxy smartphone<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Michael Grafnetter <notifications@github.com> </div><div>Date: 8/7/16  7:07 AM  (GMT-05:00) </div><div>To: MichaelGrafnetter/DSInternals <DSInternals@noreply.github.com> </div><div>Cc: kevindelafield <kevindelafield@hotmail.com>, Author <author@noreply.github.com> </div><div>Subject: Re: [MichaelGrafnetter/DSInternals] query by upn rather than samaccount, guid or sid (#18) </div><div>
</div>
This change has been just released in v 2.16.

---
