### ISSUE TITLE
Test-PasswordQuality directly with SPLIT database from HIBP

### ISSUE THREAD

**Issue by gruppenrichtlinien** [MichaelGrafnetter/DSInternals#185]
Test-PasswordQuality and the parameter -WeakPasswordHashesSortedFile or -WeakPasswordHashesFile is using the single file, e.g. fom HIBP.

Actually I use two seperate versions of the HIBP File: Single and Split into 00000-FFFFF.txt, the SPLIT files are more performant, when checking how often the hash is in the breached list.

For Data Reduction reasons, it would be nice to have only the split version and a parameter like " -WeakPasswordHashesFilePath"

**Comment by MichaelGrafnetter** [comment]
Hello @gruppenrichtlinien , would you please be able to implement this feature?

**Comment by gruppenrichtlinien** [comment]
Sorry, I think it´s my problem in understanding.

The reason, why I use the split files is, not to get the count of compromised accounts in the AD. The reason to use the split is the faster search for the counter how often a specific NTLM hash is inside the database. 
An appearence of 10.000+ is much more faster to reset, than one with a count of 10.

the counter is inside the .txt files, seperated by ":"

If I search for the specific Hash in 30GB it took a long time ...

**Comment by aseigler** [comment]
Understood. It's implemented in #186.
