### ISSUE TITLE
Import Module in c# DLL

### ISSUE THREAD

**Issue by mwangepatrick** [MichaelGrafnetter/DSInternals#19]
I am trying to import the DSInternals module for use in my C# dll. 

when using the powershell, everything works just fine but this code does not seem to load the module. 

Any idea on what am doing wrong?
  ```
            InitialSessionState init = InitialSessionState.CreateDefault();
            init.ImportPSModule(new string[] { @"D:\\DSInternals\\dsinternals.psd1" });
            Runspace runspace = RunspaceFactory.CreateRunspace(init);
            runspace.Open();
            PowerShell ps = PowerShell.Create();
            ps.Runspace = runspace;
            ps.Commands.AddCommand("Get-ADReplAccount");

            foreach (PSObject result in ps.Invoke())
            {
                Console.WriteLine(result); //this always returns null
            }
            
 
```

**Comment by MichaelGrafnetter** [comment]
As already discussed on Twitter, in C# projects, the official [DSInternals NuGet](https://www.nuget.org/profiles/MichaelGrafnetter) libraries should be used instead of invoking the PowerShell cmdlets.

**Comment by rios0rios0** [comment]
> As already discussed on Twitter, in C# projects, the official [DSInternals NuGet](https://www.nuget.org/profiles/MichaelGrafnetter) libraries should be used instead of invoking the PowerShell cmdlets.

Is there some example of how to do it, avoiding recreating all useful cmdlets?

**Comment by MichaelGrafnetter** [comment]
> Is there some example of how to do it, avoiding recreating all useful cmdlets?

Yes, see the [source code of the PowerShell module itself](https://github.com/MichaelGrafnetter/DSInternals/tree/master/Src/DSInternals.PowerShell), which is written in C# and uses the libraries to do all the heavy lifting.

**Comment by rios0rios0** [comment]
> > Is there some example of how to do it, avoiding recreating all useful cmdlets?
> 
> Yes, see the [source code of the PowerShell module itself](https://github.com/MichaelGrafnetter/DSInternals/tree/master/Src/DSInternals.PowerShell), which is written in C# and uses the libraries to do all the heavy lifting.

Sorry, but I didn't find the documentation to do what I want...
For example: ````new TestPasswordQualityCommand().Execute()"```.
Is there a way to use the commands and not the classes only?

**Comment by MichaelGrafnetter** [comment]
> Is there a way to use the commands and not the classes only?

There of course is a way to create your own PowerShell host, but don't do it. Just copy out the C# code from a cmdlet and modify it to your needs.

**Comment by rios0rios0** [comment]
> > Is there a way to use the commands and not the classes only?
> 
> There of course is a way to create your own PowerShell host, but don't do it. Just copy out the C# code from a cmdlet and modify it to your needs.

Ok, so, I'll have some work modifying to use with C# right?
There's no simple way, like import and use it...

Thanks for the answer.

**Comment by MichaelGrafnetter** [comment]
Most of the cmdlets only contain a couple of lines of code. This one is an exception.
