### ISSUE TITLE
feature request: password audit without password disclosure

### ISSUE THREAD

**Issue by roycewilliams** [MichaelGrafnetter/DSInternals#21]
For some job roles and policy environments, it would be preferable if the person performing the audit has no direct knowledge of the actual passwords used. It would be good for `Test-PasswordQuality` to have a flag/option to suppress displaying passwords to the screen and in any reports.  In other words, instead of this output:

```
Passwords of these accounts have been found in the dictionary:
  adam                Pa$$w0rd
  peter               July2016
 
Historical passwords of these accounts have been found in the dictionary:
  april               Pa$$w0rd
  brad                Pa$$w0rd
```

... this output:

```
Passwords of these accounts have been found in the dictionary:
  adam
  peter
 
Historical passwords of these accounts have been found in the dictionary:
  april
  brad
```
If this is already an option, please consider this to be a documentation clarification request. :)

**Comment by MichaelGrafnetter** [comment]
I actually could not make up my mind whether to display the passwords or not. That is why the cleartext ones do not get displayed. Adding an option for that is a good idea.

**Comment by roycewilliams** [comment]
Indeed!  Not being able to make up your mind is probably a sign that the user may want to choose. :)

**Comment by roycewilliams** [comment]
Thanks - giving the user the option is a great approach. Much appreciated.

**Comment by MichaelGrafnetter** [comment]
Oops, I made a mistake when writing the changelog, see commit d851857975fbd1fccc507b32fee17fe67675c10b.
