### ISSUE TITLE
The distinguished name specified for this replication operation is invalid

### ISSUE THREAD

**Issue by MichaelGrafnetter** [MichaelGrafnetter/DSInternals#23]
A few users have reported that they sometimes see an error with message "The distinguished name specified for this replication operation is invalid" instead of "Access denied" when using the Get-ADReplAccount cmdlet.

**Comment by ars1s** [comment]
Any news about the issue?

**Comment by MichaelGrafnetter** [comment]
This bugfix will be present in the next release of DSInternals. It is actually a workaround, because Microsoft's API itself returns error DS_DRA_BAD_DN instead of DS_DRA_ACCESS_DENIED. So after encountering this error, I send another request to the DC, asking it to transtate this DN into GUID, to check its existence. But it will still not work under some very rare circumstances.
