### ISSUE TITLE
Cannot Import Module

### ISSUE THREAD

**Issue by benichmt1** [MichaelGrafnetter/DSInternals#28]
![dsint](https://cloud.githubusercontent.com/assets/1136610/18179650/7bbde2ee-7051-11e6-9d1f-af5f8fd4d055.png)
For some reason, I can't install this on Server 2008 R2, x64 because of the above error.

**Comment by MichaelGrafnetter** [comment]
You are probably using PowerShell 2, while the module [requires](https://github.com/MichaelGrafnetter/DSInternals/wiki/Installation#system-requirements) PowerShell 3+. Try installing a newer version of the Windows Management Framework.
One would expect to see this message about unsupported version right away. Unfortunately, this behavior has also been added in PS3.
