### ISSUE TITLE
Replication does not work for Protected Users

### ISSUE THREAD

**Issue by MichaelGrafnetter** [MichaelGrafnetter/DSInternals#35]
It has been reported that the Get-ADReplAccount cmdlet does not work when it is executed by users who are members of the Protected Users group. I will have to verify that.

**Comment by FabienLavocat** [comment]
Only adding the SPN to the RPC binding was enough to fix the issue of users member of the Protected Users group?

**Comment by MichaelGrafnetter** [comment]
@FabienLavocat Yes, this tiny change actually added support for Kerberos authentication. Previously it only worked with NTLM, which is disabled for Protected Users.
