### ISSUE TITLE
2008 R2 module cannot be imported because its manifest contains one or more members that are not valid

### ISSUE THREAD

**Issue by focalfury** [MichaelGrafnetter/DSInternals#37]
I've tested this on multiple 2008R2 machines.  When attempting to run "Import-Module DSInternals" in powershell, the following text in the output below is returned stating.  Method of installation was downloading zip, and extracting it to the Modules directory as instructed in 2a of the Readme.txt

Multiple tests of 2012R2 do not have this problem, and comparing the 2008/2012 directories have the same files and sizes.

Here is the error output below.

Import-Module : The 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\dsinternals\dsinternals.psd1' module cannot be
imported because its manifest contains one or more members that are not valid. The valid manifest members are ('ModuleT
oProcess', 'NestedModules', 'GUID', 'Author', 'CompanyName', 'Copyright', 'ModuleVersion', 'Description', 'PowerShellVe
rsion', 'PowerShellHostName', 'PowerShellHostVersion', 'CLRVersion', 'DotNetFrameworkVersion', 'ProcessorArchitecture',
 'RequiredModules', 'TypesToProcess', 'FormatsToProcess', 'ScriptsToProcess', 'PrivateData', 'RequiredAssemblies', 'Mod
uleList', 'FileList', 'FunctionsToExport', 'VariablesToExport', 'AliasesToExport', 'CmdletsToExport'). Remove the membe
rs that are not valid ('RootModule'), then try to import the module again.
At line:1 char:14
+ import-module <<<<  dsinternals
    + CategoryInfo          : InvalidData: (C:\Windows\syst...sinternals.psd1:String) [Import-Module], InvalidOperatio
   nException
    + FullyQualifiedErrorId : Modules_InvalidManifestMember,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by MichaelGrafnetter** [comment]
Hi @focalfury , please try installing PowerShell 3+ on that Windows Server 2008 R2 box. PS2 throws this error when it sees a PS3+ manifest and there probably is no way of fixing it.

**Comment by MichaelGrafnetter** [comment]
See #28

**Comment by focalfury** [comment]
ooof sorry this was a duplicate :(   This fixed it.  Thank you for your time
