### ISSUE TITLE
Replication cmdlets do not work against Windows Server 2003

### ISSUE THREAD

**Issue by MichaelGrafnetter** [MichaelGrafnetter/DSInternals#4]
The replication cmdlets throw error “The distinguished name specified for this replication operation is invalid.” when executed against Windows Server 2003.

**Comment by nbevans** [comment]
https://github.com/CoreSecurity/impacket/commit/e6ec7297eb4b4799a6e048222a7e27dc03a2d1fa

**Comment by MichaelGrafnetter** [comment]
Thx, @nbevans, that's it.

**Comment by MichaelGrafnetter** [comment]
@nbevans It turns out that I have already been using the correct flags since the beginning. I have now successfully tested the replication cmdlets against a Windows Server 2003 R2 DC in Windows 2000 Mixed Domain Functional Level. It is possible that the person who reported this bug to me has just mistyped the domain naming context.

**Comment by nbevans** [comment]
Great!
