### ISSUE TITLE
Can't import DSInternals

### ISSUE THREAD

**Issue by kennethkc** [MichaelGrafnetter/DSInternals#41]
Failed to import DSInternals with error message below with Win7 (64bit)
Tried WMF5.0 and 5.1 and .Net 4.5.1 and 4.5.2 with no luck

PS C:\WINDOWS\system32> import-module DSInternals
Add-Type : Could not load file or assembly
'file:///C:\Windows\System32\WindowsPowerShell\v1.0\Modules\DSInternals\x86\DSInternals.Replication.Interop.dll' or
one of its dependencies. An attempt was made to load a program with an incorrect format.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\DSInternals\DSInternals.psm1:16 char:5
     Add-Type -Path $interopAssemblyPath
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], BadImageFormatException
    + FullyQualifiedErrorId : System.BadImageFormatException,Microsoft.PowerShell.Commands.AddTypeCommand

**Comment by MichaelGrafnetter** [comment]
That's too bad.  It seems like if the 64-bit PS was trying to load the 32-bit library instead of the 64-bit one, which is strange.

What does $env:PROCESSOR_ARCHITECTURE resolve to when this problem appears?

Are you running PowerShell 64-bit or 32-bit (x86)? Could you please try the other one on your Win7 64-bit?

Could you please try the same with a previous version of DSInternals? I switched to VS 2017 + Win10 build machine before creating the most recent release and I did not have enough time to test it on all downlevel systems.

**Comment by kennethkc** [comment]
i am using PS 64-bit, i printed the variable interopAssemblyPath and env:PROCESSOR_ARCHITECTURE below

> 
> PS C:\WINDOWS\system32> Import-Module DSInternals
> WARNING:
> interopAssemblyPath=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\DSInternals\AMD64\DSInternals.Replication.Intero
> p.dll
> WARNING: env:PROCESSOR_ARCHITECTURE=AMD64
> Add-Type : Could not load file or assembly 'DSInternals.Replication.Interop.dll' or one of its dependencies. The
> specified module could not be found.
> At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\DSInternals\DSInternals.psm1:20 char:5
> +     Add-Type -Path $interopAssemblyPath
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundException
>     + FullyQualifiedErrorId : >System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.AddTypeCommand

i copied the module to syswow64 and run the PS 32-bit

> PS C:\WINDOWS\system32> Import-Module DSInternals
> WARNING:
> interopAssemblyPath=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\DSInternals\x86\DSInternals.Replication.Interop.
> dll
> WARNING: env:PROCESSOR_ARCHITECTURE=x86
> Add-Type : Could not load file or assembly 'DSInternals.Replication.Interop.dll' or one of its dependencies. The
> specified module could not be found.
> At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\DSInternals\DSInternals.psm1:20 char:5
> +     Add-Type -Path $interopAssemblyPath
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundException
>     + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.AddTypeCommand
>

**Comment by kennethkc** [comment]
i tried the version 2.20 and now I can import the module with no error message. i will try more on it. thanks for your help

**Comment by kennethkc** [comment]
i think it would be good if the function to remove LMHash and LMHashHistory could be added and actually it is the task which i am focusing on actually

**Comment by MichaelGrafnetter** [comment]
@kennethkc LMHash is a completely different story. The only supported way of deleting it is by setting the appropriate policy and changing the password. I could only imagine that the hash could be deleted by direct manipulation with the ntds.dit file. I you think that would be useful to you, feel free to file a separate feature request.

**Comment by MichaelGrafnetter** [comment]
@kennethkc I have just pushed a new release. Could you please try it in the same way as you did previously?

**Comment by kennethkc** [comment]
I got another error for running with v2.21.1.zip

> PS C:\WINDOWS\system32> Import-Module DSInternals
> Import-Module : Could not load file or assembly
> 'file:///C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\DSInternals\DSInternals.PowerShell.dll' or one of its
> dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
> At line:1 char:1
> + Import-Module DSInternals
> + ~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
>     + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by MichaelGrafnetter** [comment]
Hi @kennethkc , could you please double-check that all the files (and specifically those 2 DSInternals.Replication.Interop.dll) are "unblocked"?

**Comment by kennethkc** [comment]
my apologies for missing to unblock the files. i can import the module successfully with v2.21.1.
thanks for your time and effort!
