### ISSUE TITLE
"Input string was not in a correct format."

### ISSUE THREAD

**Issue by Foneman38** [MichaelGrafnetter/DSInternals#42]
System Hive and ntds.dit exported from Windows Server 2003 Standard Edition with SP1 (English)

Get-ADDBAccount : Cannot bind parameter 'BootKey'. Cannot convert value "13d20976d63ea5e836036ec8bc68d6eb" to type
"System.Byte". Error: "Input string was not in a correct format."
At line:1 char:66
+ Get-ADDBAccount -All -DBPath 'D:\ntds.dit' -BootKey $key
+                                                                  ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ADDBAccount], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,DSInternals.PowerShell.Commands.GetADDBAccountCommand

PS C:\Windows\system32> $key
13d20976d63ea5e836036ec8bc68d6eb

**Comment by MichaelGrafnetter** [comment]
That is strange. Could you please try to run these 2 commands?

Get-ADDBAccount -All -DBPath 'D:\ntds.dit' -BootKey '13d20976d63ea5e836036ec8bc68d6eb'
Get-ADDBAccount -All -DBPath 'D:\ntds.dit' -BootKey $key.Trim()

How exactly did you populate the $key variable?

**Comment by MichaelGrafnetter** [comment]
@Foneman38 Could you please also check that $key.GetType().Name really is String? What version of PowerShell do you have?

**Comment by MichaelGrafnetter** [comment]
I have done a couple of more tests and it turned out that my code did not work if the String was encapsulated in a PSObject.

**Comment by MichaelGrafnetter** [comment]
Hi @Foneman38 , could you please test the latest release? Thanks.

**Comment by Foneman38** [comment]
Version    Name                                Type       Repository           Description
-------    ----                                ----       ----------           -----------
2.21.2     DSInternals                         Module     PSGallery            The DSInternals PowerShell Module

This is what I get with 
Get-ADDBAccount -All -DBPath 'D:\ntds.dit' -BootKey '13d20976d63ea5e836036ec8bc68d6eb'
 Get-ADDBAccount -All -DBPath 'D:\ntds.dit' -BootKey $key.Trim()
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**Get-ADDBAccount : Secondary index is corrupt. The database must be defragmented or the affected index must be deleted.
If the corrupt index is over Unicode text, a likely cause is a sort-order change.
At line:1 char:1
+ Get-ADDBAccount -All -DBPath "D:\Stevens\ntds\ntds.dit" -BootKey $key ...
+     + CategoryInfo          : OpenError: (:) [Get-ADDBAccount], EsentSecondaryIndexCorruptedException
    + FullyQualifiedErrorId : DBContextError,DSInternals.PowerShell.Commands.GetADDBAccountCommand**

**Comment by MichaelGrafnetter** [comment]
@Foneman38 This is expected behavior. Have you tried to defragment the DB using esentutl.exe, as the message says? The PS module is using native Windows ESE library to read the DB and this library has issues with backwards compatibility.
