### ISSUE TITLE
Get-ADReplAccount : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by mattdreher** [MichaelGrafnetter/DSInternals#43]
It would seem that I have run into another error on some user accounts.  When I run this command on specific users:
`Get-ADReplAccount -SamAccountName TestUser1 -Domain Domain -Server Server`

I get the following error:
```
Get-ADReplAccount : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ADReplAccount -SamAccountName TestUser1 -Domain Domain -Server Server ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ADReplAccount], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,DSInternals.PowerShell.Commands.GetADReplAccountCommand
```

Here is the stack trace:
```
   at DSInternals.Common.Data.DSAccount.LoadRoamedCredentials(DirectoryObject dsObject)
   at DSInternals.Common.Data.DSAccount..ctor(DirectoryObject dsObject, DirectorySecretDecryptor pek)
   at DSInternals.Replication.DirectoryReplicationClient.GetAccount(Guid objectGuid)
   at DSInternals.PowerShell.Commands.GetADReplAccountCommand.ReturnSingleAccount()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

I have a few users that have this issue.  I am also getting the error if I use -All parameter and it kills the command.

**Comment by MichaelGrafnetter** [comment]
I hope to have resolved it, @mattdreher . I will try to roll out a new release today. I wonder if you could please test it afterwards.

**Comment by mattdreher** [comment]
Sure thing @MichaelGrafnetter.  Just ping me through here when it is ready.

**Comment by MichaelGrafnetter** [comment]
@mattdreher It's out. Fingers crossed.

**Comment by mattdreher** [comment]
@MichaelGrafnetter, Everything seems to be working properly now.  I have tried both with a single user and with the Get-ADReplAccount -All.  Thanks for your assistance.

**Comment by MichaelGrafnetter** [comment]
Thanks, @mattdreher, for testing it.
