### ISSUE TITLE
Databases from WS 2016 cannot be opened on non-DCs

### ISSUE THREAD

**Issue by MichaelGrafnetter** [MichaelGrafnetter/DSInternals#45]
When you try to open a ntds.dit file from Windows Server 2016 on Windows 10, you get error _JET_errCallbackNotResolved_, "A callback function could not be found", pointing to a missing ntdsai.dll file. This file is only present on DCs and LDS servers. Thanks to @ZilentJack for reporting this issue.

I will try to play with the JET_paramDisableCallbacks system parameter that might bypass this issue.

**Comment by tylerapplebaum** [comment]
Hi Michael, do you have a sample NTDS.dit and SYSTEM hive that you can post so we can test?

**Comment by c0d3z3r0** [comment]
ntdsai.dll is missing even on WS 2016 (fresh install)

**Comment by MichaelGrafnetter** [comment]
Yes, @c0d3z3r0, even a clean install of WS2016 is missing AD DS/AD LDS components. Adding them through the Server Manager (without dcpromo) should solve the issue for now.
Note that these components are also part of AD LDS for Windows 10.

**Comment by c0d3z3r0** [comment]
Aaah, thanks! :-)
