### ISSUE TITLE
schema without samaccounttype 

### ISSUE THREAD

**Issue by manu18** [MichaelGrafnetter/DSInternals#46]
Hi Michael. I have a problem I hope you can help with.
My directory schema not contain samaccounttype or samaccountname so i try using -ObjectGuid and surprise :

```
Get-ADDBAccount -ObjectGuid xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx -DBPath ‘C:\prj\adamntds.dit’ -BootKey $key
Get-ADDBAccount : Directory schema does not contain attribute ‘sAMAccountType’.
Au caractère Ligne:1 : 1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Get-ADDBAccount], SchemaAttributeNotFoundException
+ FullyQualifiedErrorId : DSInternals.Common.Exceptions.SchemaAttributeNotFoundException,DSInternals.PowerShell.Co
mmands.GetADDBAccountCommand

```
Best regards

**Comment by MichaelGrafnetter** [comment]
Thanks for pointing that out. I did not have time to add full LDS support to my cmdlets yet. But I am aware of this problem, see #5 . The main problem is in the schema (as you have noticed) which is different from the AD and even the basic things are highly customizable.
