### ISSUE TITLE
Get-BootKey : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by 304GEEK** [MichaelGrafnetter/DSInternals#47]
Get-BootKey : Object reference not set to an instance of an object.
At /Users/dixon_r/Downloads/DSInternals_v2/fetchhashes.ps1:5 char:8
+ $key = Get-BootKey -SystemHivePath 'SYSTEM'
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Get-BootKey], NullReferenceException
    + FullyQualifiedErrorId : GetBootKey_OtherError,DSInternals.PowerShell.Commands.GetBootKeyCommand

I feel I'm doing something wimple and wrong.

any ideas?

**Comment by chlob** [comment]
Hi, I have the same error. I tested with the sample files of Didier Stevens (https://blog.didierstevens.com).

When I examined the stack trace I found an error, which says, that It did not found "DSInternals.Replication.Interop.dll", because it does not exist. Any ideas?

BR
Christoph

**Comment by MichaelGrafnetter** [comment]
Hi @chlob, could you please check that 2 such DLL file are contained in the module you have acquired and that they are unblocked?
