### ISSUE TITLE
Importing the powershell modules

### ISSUE THREAD

**Issue by jomivz** [MichaelGrafnetter/DSInternals#48]
Hello Michael

I am using Powershell 3.0. I have an issue importing the powershel modules.

Here are my steps before doing 'import-module :
- downloading the repository DSInternals as a ZIP
- copying DSInternals-master.zip\DSInternals-master\Src\DSInternals.powershell into C:\windows\system32\WindowsPowerShell\v1.0\Modules

**Comment by jomivz** [comment]
Here is the output of the command 'import-module dsinternals':

`PS C:\windows\system32> import-module dsinternals.powershell

import-module : The specified module 'dsinternals.powershell' was not loaded because no valid module file was found in any

module directory.

At line:1 char:1

+ import-module dsinternals.powershell

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : ResourceUnavailable: (dsinternals.powershell:String) [Import-Module], FileNotFoundException

    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

 

PS C:\windows\system32> import-module dsinternals

import-module : The specified module 'dsinternals' was not loaded because no valid module file was found in any module

directory.

At line:1 char:1

+ import-module dsinternals

+ ~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : ResourceUnavailable: (dsinternals:String) [Import-Module], FileNotFoundException

    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand`

**Comment by leomatias** [comment]
Same issue, any clue?

**Comment by MichaelGrafnetter** [comment]
Hi @leomatias and @jomivz, if you download the source codes (DSInternals-master.zip), then you need to compile it all yourselves to get those DLL files. You should rather download the pre-compiled module from the [Releases](https://github.com/MichaelGrafnetter/DSInternals/releases/latest) page.
