### ISSUE TITLE
Test-PasswordQuality : Object reference not set to an instance of an object. At line:1 char:19

### ISSUE THREAD

**Issue by hkelley** [MichaelGrafnetter/DSInternals#50]
When I run a test using the -SkipDuplicatePasswordTest switch I always get this error

PS C:\Temp> $adReplica | Test-PasswordQuality  -WeakPasswordHashes $p1  -SkipDuplicatePasswordTest
Test-PasswordQuality : Object reference not set to an instance of an object.
At line:1 char:14

The same command without that switch runs fine.   Has this been encountered before?  The -debug switch isn't telling me anything helpful

**Comment by MichaelGrafnetter** [comment]
Thanks @hkelley, this seems to be a bug. Could you please post the entire stack trace so that I can pinpoint it?
