### ISSUE TITLE
There are no more endpoints available from the endpoint mapper.

### ISSUE THREAD

**Issue by zeemaffin** [MichaelGrafnetter/DSInternals#54]
Hello! 

I tried to Run : 

$DictFile = "C:\PasswordDict.txt"
$DC = "DC1"
$Dict = Get-Content $DictFile | ConvertTo-NTHashDictionary
Get-ADReplAccount -All -Server Server -NamingContext "dc=dc1,dc=dc2" |
   Test-PasswordQuality -WeakPasswordHashes $Dict -ShowPlainTextPasswords -IncludeDisabledAccounts

And i got the followng error 

There are no more endpoints available from the endpoint mapper. 
It has a problem with Get-AD.... 

Maybe i m just a fool, can some1 help me? :)

**Comment by MichaelGrafnetter** [comment]
Hey @zeemaffin, as the error message says, you obviously have some trouble at the RPC/Replication layer on your DC and it most probably has nothing to do with DSInternals. Try to do some [troubleshooting](https://support.microsoft.com/en-us/help/2089874/troubleshooting-ad-replication-error-1753-there-are-no-more-endpoints).
