### ISSUE TITLE
ConvertTo-NTHashDictionary is not available in newest published module

### ISSUE THREAD

**Issue by PrzemyslawKlys** [MichaelGrafnetter/DSInternals#57]
There is this article https://www.dsinternals.com/en/auditing-active-directory-password-quality/ that uses `ConvertTo-NtHashDictionary` but it seems it's not in .psd1 anymore. Something has changed... is there replacement for it in newest version (also usage one - I tried `ConvertTo-NtHash` but it's for something else right?

**Comment by MichaelGrafnetter** [comment]
You are right. I have to update the article, as there had been a major change in version 3.0.
The functionality is now integrated directly into Test-PasswordQuality. It has 3 optional weak password-related parameters:

- WeakPasswords -Accepts one or more passwords directly from command line.
- WeakPasswordsFile - Expects a path to a file containing bad passwords, one per line.
- WeakPasswordHashesFile - Expects a path to a file containing password hashes, one per line (like the one from HaveIBeenPwned)
