### ISSUE TITLE
Get-ADReplAccount - Proper PS object

### ISSUE THREAD

**Issue by PrzemyslawKlys** [MichaelGrafnetter/DSInternals#60]
Can you also consider updating `Get-ADReplAccount` to be real PSCustomObject or similar? Right now it displays stuff to screen but when you try to access it it's hit or miss scenario.

For example it displays:
```
Secrets:
   NTHash: ....
   LMHash: ...
```
But `Secrets` it's not a valid property.

**Comment by MichaelGrafnetter** [comment]
The *Secrets* section is there just to aid readability. But properties NTHash and LMHash are there. You even get code completion in `Where-Object` and `Foreach-Object` as Get-ADReplAccount returns strongly typed `DSAccount` .NET objects.

**Comment by PrzemyslawKlys** [comment]
I understand this and secrets was just an example. But the way you display everything in this 

```
   KerberosNew:
      Credentials:
        AES256_CTS_HMAC_SHA1_96
```

It seems like it's accessible by .KerberosNew.Credentials.AES.. when it isn't. But I accept your decision. Thanks!
