### ISSUE TITLE
Port C++ code to become fully managed

### ISSUE THREAD

**Issue by loudadyassine** [MichaelGrafnetter/DSInternals#66]
Hi,

I need my application to be hosted on Linux, Is there any way to make the nuget package work in another environment than Windows ? I have seen that there is a lot of C++ code, could it be ported to .net or there are some dependencies on some windows libraries ?

Yassine,

**Comment by FabienLavocat** [comment]
A lot of the code is using Windows RPC libraries so I think it would be quite complex to have the code to work on Linux.

**Comment by MichaelGrafnetter** [comment]
I agree with @FabienLavocat . There actually is a [fully managed implementation of MS-DRSR](https://github.com/Microsoft/WindowsProtocolTestSuites) directly from Microsoft, but it also requires some native Windows libraries. I am considering to implement some DSInternals tests based on that code, but I have to look more deeply into it.
