### ISSUE TITLE
was ConvertTo-NTHashDictionary removed?

### ISSUE THREAD

**Issue by unassassinable** [MichaelGrafnetter/DSInternals#67]
Installed the newer 3.0 release, running ISE as local admin, and looking at the DSInternals Module, I don't see the ConvertTo-NTHashDictionary commandlet anywhere.  
![image](https://user-images.githubusercontent.com/14897048/49530228-0eebda00-f875-11e8-987f-a62a77a3f89e.png)

**Comment by MichaelGrafnetter** [comment]
The functionality has been integrated (and extended) into the `Test-PasswordQuality` cmdlet. Use any combination of the `-WeakPasswords`,  `-WeakPasswordsFile` and `-WeakPasswordHashesFile` parameters. And NTLM hashes from [HaveIBeenPwned](https://haveibeenpwned.com/Passwords) are also supported.
