### ISSUE TITLE
Test-PasswordQuality - key ShowPlainTextPasswords in not available

### ISSUE THREAD

**Issue by kutsev** [MichaelGrafnetter/DSInternals#69]
Hi!
In version 2.22 I was able copy plain text password in result file using the key -ShowPlainTextPasswords of Test-PasswordQuality cmdlet .
In version 3.0 this key is not available.
Can you please check?

**Comment by MichaelGrafnetter** [comment]
Hello @kutsev, after much thinking, I have intentionally removed this feature in version 3.0:
- The main use case is now checking passwords against HaveIBeenPwned, which only provides hashes, so the actual passwords cannot be shown.
- Several IT managers have told me that they would prefer if the auditor did not see the actual passwords.

What is your opinion?

**Comment by kutsev** [comment]
I understand your opinion, in most situation, I think, if password match some weak password database, it should be changed, no matter what password actually it is.

Nowadays I have a task from security team to audit users with certain passwords and know what certain password was used (because it was possible that someone of the IT team assigned such password to users and that's their responsibility).

Ok, in case I'll need the plain text password, I will use old version. Thank you

**Comment by MichaelGrafnetter** [comment]
Thanks for your feedback. I might give it another thought in the future.
Yes, one approach is using the old version. Or you could split your dictionary into multiple files / command lines and run `Test-PasswordQuality` multiple times to identify users with those specific passwords that might have been assigned by administrators.
