### ISSUE TITLE
Add support for incremental replication

### ISSUE THREAD

**Issue by MichaelGrafnetter** [MichaelGrafnetter/DSInternals#7]
Add support for incremental replication using a cookie to the DSInternals.Replication library. Although the replication cookie is used internally, it is not exposed to the user of the library.

**Comment by nbevans** [comment]
What will this feature be used for?

**Comment by MichaelGrafnetter** [comment]
With this feature, you could fetch only accounts that have been changed since the last replication with a specific DC.This might be useful for some identity management stuff and it is what DCs actually do during standard replication.

**Comment by nbevans** [comment]
That sounds great for what we are using your library for :) Currently we are refreshing all accounts from scratch every hour. But if we can store a cookie and give it back to DSInternals when we want to refresh and only get back the changed items then that would be awesome.

**Comment by MichaelGrafnetter** [comment]
The only downside is that the cookie is DC-specific, meaning that if it dies,you are back at resyncing.

**Comment by MichaelGrafnetter** [comment]
There has been a breaking change in commit c6fb24c78cedeba8ddecf51f2bc83ad1525f4a54. Since version 2.17, the cookie is immutable and a delegate is used to monitor replication progress and to retrieve the current cookie.
