### ISSUE TITLE
'Microsoft.Isam.Esent.Interop.Api' threw an exception

### ISSUE THREAD

**Issue by Filk47473831** [MichaelGrafnetter/DSInternals#86]
Get the following error-

Get-ADDBAccount : The type initializer for 'Microsoft.Isam.Esent.Interop.Api' threw an exception.                                 At /root/pwcheck/pwcheck.ps1:1 char:1                                                                                             + Get-ADDBAccount -All -DBPath ntds.dit -BootKey 4e439b5d264f1f475c52d5 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (:) [Get-ADDBAccount], TypeInitializationException
+ FullyQualifiedErrorId : DBContextError,DSInternals.PowerShell.Commands.GetADDBAccountCommand

Using this command-

Get-ADDBAccount -All -DBPath ntds.dit -BootKey 4e439b5d264f1f475c52d57100cc83ab | Test-PasswordQuality -WeakPasswordHashesFile passwords.txt -IncludeDisabledAccounts | Out-File results.txt

Any ideas?

I've installed Powershell using the 'snap install powershell --classic' command on Ubuntu 18.04

**Comment by MichaelGrafnetter** [comment]
Hi, DSInternals uses esent.dll, a native Windows library, for AD database operations. As a consequence, Linux is not a supported platform for running DSInternals.

Michael Grafnetter
________________________________
