### ISSUE TITLE
Display Name and CSV

### ISSUE THREAD

**Issue by Judoboy6** [MichaelGrafnetter/DSInternals#87]
Hi,

I use the following command every month :

Get-ADReplAccount -All -NamingContext 'DC=contoso,DC=com' -Server dc1.contoso.com | Test-PasswordQuality -WeakPasswordsFile BadPasswords.txt

This is very usefull, but the output is not very easy to use.
Is it possible to have a CSV as output, with the DisplayName and Email of the user in addition to the SamAccountName ?

Thanks,

**Comment by MichaelGrafnetter** [comment]
Hi @Judoboy6, with just a few accounts, you could do something like this:

```powershell
$accounts = Get-ADReplAccount -All -NamingContext 'DC=contoso,DC=com' -Server dc1.contoso.com
$results = $accounts | Test-PasswordQuality -WeakPasswordsFile BadPasswords.txt
$riskyAccounts = $accounts | where SamAccountName -in $results.WeakPassword
$riskyAccounts | select SamAccountName,DisplayName,DistinguishedName | Export-Csv output.csv
``` 

Note that the current version of DSInternals does not retrieve the `mail` attribute.

**Comment by Judoboy6** [comment]
Thanks.

**Comment by CSSx3** [comment]
Hello Michael,

I am currently working on automating this so that users receive an email when a weak password is detected.

Unfortunately, the csv export does not work for me, or only 0 kb is displayed. Do you have any idea what could be the reason for this?

I also tried with $results.PasswordNeverExpire, this was also not working.

**Comment by MichaelGrafnetter** [comment]
Hi @CSSx3 , there had been a change in DSInternals since I have written the code sample above, to support cross-domain comparisons. The `LogonName` property needs to be used in the current version of DSInternals instead of `SamAccountName` in the `Where-Object` filter clause.

**Comment by CSSx3** [comment]
Looks better, thanks for the quick help!

**Comment by shudman** [comment]
Can someone point me in the direction of using the above with a filter ?  I have tried unsuccessfully to use Get-ADReplAccount with a where-object and get in all world of pain (not really a PSher).
The bottom line is, I am trying to get filtered users, and have the output with mail or another attrib, as well as samaccountname

This works fine, just I need displayname or mail in the output:
Get-ADUser -Filter * -server dc1.domain.com -SearchBase "OU=User Accounts,DC=domain,DC=com" | Where-Object {$_.DistinguishedName -notlike "*Sea*"} | Select ObjectGuid | Get-ADReplAccount -Server dc1.domain.dom | Test-PasswordQuality -WeakPasswordsFile "c:\temp\200_passwords.txt" | select SamAccountName,DisplayName,DistinguishedName | export-csv c:\temp\output.csv

**Comment by MichaelGrafnetter** [comment]
@shudman If you want to get the `DisplayName` attribute, you need to split the pipeline, similarly to the example above:
```powershell
$accounts = Get-ADReplAccount -All -NamingContext 'DC=contoso,DC=com' -Server dc1.contoso.com |
    Where-Object DistinguishedName -like '*,OU=User Accounts,DC=contoso,DC=com'  |
    Where-Object DistinguishedName -notlike '*Sea*'
$results = $accounts | Test-PasswordQuality -WeakPasswordsFile BadPasswords.txt
$riskyAccounts = $accounts | Where-Object LogonName -in $results.WeakPassword
$riskyAccounts | Select-Object -Property SamAccountName,DisplayName,DistinguishedName | Export-Csv output.csv
```

OR

```powershell
$accounts = Get-ADUser -Filter { Enabled -eq $true} -Server dc1.contoso.com -SearchBase 'OU=User Accounts,DC=contoso,DC=com' |
    Where-Object DistinguishedName -notlike '*Sea*' |
    Select-Object -Property ObjectGuid |
    Get-ADReplAccount -Server dc1.contoso.com
$results = $accounts | Test-PasswordQuality -WeakPasswordsFile BadPasswords.txt
$riskyAccounts = $accounts | Where-Object LogonName -in $results.WeakPassword
$riskyAccounts | Select-Object -Property SamAccountName,DisplayName,DistinguishedName | Export-Csv output.csv
```

This is not the most efficient way of doing it in environments with millions of accounts, but it should be OK for most orgs.

**Comment by shudman** [comment]
Perfect thank you @MichaelGrafnetter - works perfectly.  I assume DSinternals still does not "receive" the mail attribute ?

**Comment by MichaelGrafnetter** [comment]
> I assume DSinternals still does not "receive" the mail attribute ?

@shudman Email address retrieval is currently not implemented. But you can fetch the directly from AD over LDAP. Or from ntds.dit by using `dsamain.exe`.
