### ISSUE TITLE
The boot key provided cannot be used to decrypt the database.

### ISSUE THREAD

**Issue by ZombieSlayer-011235813** [MichaelGrafnetter/DSInternals#91]
If I run the New-ADDBRestoreFromMediascript cmdlet to generate a PowerShell script for future use with IFM data I receive the following error on the command line:

New-ADDBRestoreFromMediaScript : The boot key provided cannot be used to decrypt the database.
Parameter name: BootKey
At line:1 char:1
+ New-ADDBRestoreFromMediaScript -DatabasePath 'E:\ADIFM\Active Directo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ADDBRestoreFromMediaScript], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,DSInternals.PowerShell.Commands.NewADDBRestoreFromMediaScriptCo
   mmand

I have verified the Bootkey being used is correct by first running the Get-BootKey command.  This is being run on a Windows Server 2016 Standard Edition domain controller (version 1607).  Any ideas would be appreciated.

Regards

**Comment by MichaelGrafnetter** [comment]
Strange. Could you please double-check that the BootKey really originates from the same DC as the ntds.dit file (or from the same IFM backup)?
```powershell
Get-BootKey -SystemHiveFilePath 'E:\ADIFM\registry\SYSTEM'
```

**Comment by MichaelGrafnetter** [comment]
Also please check that the database itself is readable, e.g. by using the `Get-ADDBDomainController` cmdlet.

**Comment by ZombieSlayer-011235813** [comment]
Michael,

Hi, I compared the "online" bootkey with that generated from IFM backup and they are identical.  I verified the database is readable.  I did try generating the script on another DC in the forest (in the same domain) and discovered it worked fine.

That being said, I believe the root cause is the DC I am having trouble with was originally promoted using IFM.  It seems like the script cannot be generated if the DC was created from IFM in the first place.

The first DC that I tried to generate the script on was actually promoted using IFM backup media while the second DC was not.  So I demoted the original DC that I had the issue running the script on, re-promoted it without IFM, and then re-ran the script.  This time I was able to generate the PowerShell script without any issues.

I repeated the test again by demoting the DC, creating IFM from another DC in the same domain, then re-promoting the original DC that I had the script issue with.  Again, after completing the promotion using IFM, I received the bootkey error when I tried to generate the PowerShell script. I did recreate the IFM backup (for use with the script) after the DC promotion process completed before trying to generate the PowerShell script again.

I'm assuming the same issue would occur if the DC had been cloned but I haven't tested that. 
However, I'm not sure why promoting the DC using IFM to start with would cause the bootkey error.

Regards,
Jonathan

**Comment by MichaelGrafnetter** [comment]
WOW, great analysis, @ZombieSlayer-011235813 . If it is caused by IFM then I know exactly where to look for the bug. The pekList attribute of the domain object probably contains 2 password encryption keys, which is a case that I have not tested yet.

**Comment by MichaelGrafnetter** [comment]
The bug only appeared on Windows Server 2016+ DCs promoted using IFM. It was working fine on Win 2008 and 2012.

**Comment by MichaelGrafnetter** [comment]
Hey @ZombieSlayer-011235813 , could you please check DSInternals 3.6.1? The issue should be fixed.

**Comment by MichaelGrafnetter** [comment]
Thanks, @ZombieSlayer-011235813
