### ISSUE TITLE
https://www.dsinternals.com/ Down?

### ISSUE THREAD

**Issue by TheGn0m3** [MichaelGrafnetter/DSInternals#93]
Is it me or the webiste is down? I was trying to read the blogpost but it returns an empty website...

**Comment by MichaelGrafnetter** [comment]
Thx for notifying me. There is either an issue with my Azure Subscription or WordPress.

**Comment by TheGn0m3** [comment]
Good to be of help :)

**Comment by MichaelGrafnetter** [comment]
Restart of the website did the job. But I will have to investigate it further. Nevertheless, I am planning on migrating to GitHub Pages and this incident has probably accelerated it.
